Lint/SpecFilename:
  Description: Enforces spec filenames to have `_spec` suffix
  Enabled: false
  Severity: Warning

Lint/UselessAssign:
  Description: Disallows useless variable assignments
  Enabled: false
  Severity: Warning

Naming/ConstantNames:
  Description: Enforces constant names to be in screaming case
  Enabled: false
  Severity: Convention

Naming/BlockParameterName:
  Description: Disallows non-descriptive block parameter names
  Enabled: false
  Severity: Convention

Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Enabled: false
  Severity: Warning

Documentation/DocumentationAdmonition:
  Description: Reports documentation admonitions
  Enabled: false
  Severity: Warning

Naming/QueryBoolMethods:
  Description: Reports boolean properties without the `?` suffix
  Enabled: false
  Severity: Convention
