FROM acalabs/crystal-alpine:0.31.1

WORKDIR /app

# Install shards for caching
COPY shard.yml shard.yml

RUN shards install --production

COPY src src

# Build application
RUN crystal build src/rubber-soul.cr --release --error-trace

RUN rm -r lib src

# Run the app binding on port 3000
EXPOSE 3000
HEALTHCHECK CMD curl -I localhost:3000/api/rubber-soul/v1
CMD ["/app/rubber-soul", "-b", "0.0.0.0", "-p", "3000"]
