ARG CRYSTAL_VERSION=1.1.1
FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine

WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# Add trusted CAs for communicating with external services
RUN apk update && \
    apk add --no-cache \
        ca-certificates \
        bash \
    && \
    update-ca-certificates

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

COPY shard.yml .
COPY shard.override.yml .
COPY shard.lock .

RUN shards install --ignore-crystal-version

COPY entrypoint.sh /app/entrypoint.sh

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD ["/app/entrypoint.sh"]
