version: "3.7"

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-elastic-client-env: &elastic-client-env
  ES_HOST: ${ELASTIC_HOST:-elastic}
  ES_PORT: ${ELASTIC_PORT:-9200}

x-rethinkdb-client-env: &rethinkdb-client-env
  RETHINKDB_HOST: ${RETHINKDB_HOST:-rethink}
  RETHINKDB_PORT: ${RETHINKDB_PORT:-28015}
  RETHINKDB_DB: ${RETHINKDB_DB:-place_development}

x-search-ingest-client-env: &search-ingest-client-env
  PLACE_SEARCH_INGEST_URI: ${PLACE_SEARCH_INGEST_URI:-http://search-ingest:3000}

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-latest}
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml.input
      - ${PWD}/coverage:/app/coverage
    depends_on:
      - elastic
      - rethink
    security_opt:
      - seccomp:unconfined
    environment:
      # Service Hosts
      <<: *rethinkdb-client-env
      <<: *elastic-client-env
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      <<: *deployment-env

  elastic:
    image: blacktop/elasticsearch:${ELASTIC_VERSION:-7.9.1}
    restart: always
    environment:
      discovery.type: single-node

  rethink:
    image: rethinkdb:${RETHINKDB_VERSION:-2.4}
    restart: always
    hostname: rethink
