name: CI
on: push
jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ !matrix.stable }}
    name: "Test - crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    strategy:
      matrix:
        crystal:
          - 1.1.1
        stable: [true]
        include:
          - crystal: nightly
            stable: false
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose Test Environment
        run: ./test
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
